services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PYTHON_VERSION=${PYTHON_VERSION}
    image: python-radis
    ports:
      - "8000:5000"
    environment:
      - Name=Dipak
      - Age=28
    env_file:
      - env.txt
  redis:
    image: ${REDIS_IMAGE}