services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PYTHON_VERSION=3.10-alpine
    image: python-radis
    ports:
      - "8000:5000"
    environment:
      - Name=Dipak
      - Age=28
    env_file:
      - env.txt
  redis:
    image: "redis:alpine"